# Generated by Django 4.1.2 on 2022-10-23 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_service_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
